name: GitHub Actions Variables
on: workflow_dispatch
jobs:
  test: 
    environment: testing
    runs-on: ubuntu-latest
    steps:
      - name: Output testing environment information
        run: |
          echo "Testing environment LOG_LEVEL: ${{ vars.LOG_LEVEL }}"
          echo "Testing environment STORAGE_BUCKET_NAME: ${{ vars.STORAGE_BUCKET_NAME }}"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output repository information
        run: |
          echo "Repository LOG_LEVEL: ${{ vars.LOG_LEVEL }}"
          echo "Repository STORAGE_BUCKET_NAME: ${{ vars.STORAGE_BUCKET_NAME }}"
