#To check that secrets can't be printed
name: Secrets
on: workflow_dispatch
jobs:
  test: 
    environment: testing
    runs-on: ubuntu-latest
    steps:
      - name: Output testing environment information
        run: |
          echo "Testing environment DB_USERNAME: ${{ secrets.DB_USERNAME }}"
          echo "Testing environment DB_PASSWORD: ${{ secrets.DB_PASSWORD }}"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output repository information
        run: |
          echo "Repository DB_USERNAME: ${{ secrets.DB_USERNAME }}"
          echo "Repository DB_PASSWORD: ${{ secrets.DB_PASSWORD }}"
